#include "../../public/packets/PacketDatabase.h"
#include "../../public/packets/receive/SelfChat.h"

std::unordered_set<uint16_t> PacketDatabase::s_valid_ids;

PacketDatabase::PacketDatabase() {
    init();
}

PacketDatabase& PacketDatabase::instance()
{
    static PacketDatabase db;
    return db;
}

const packet_detail* PacketDatabase::get(const uint16_t& head)
{
    const auto& map = instance().packet_map;
    const auto it = map.find(head);
    if (it != map.end()) {
        return &it->second;
    }
    return nullptr;
}

const std::unordered_set<uint16_t>& PacketDatabase::get_all_ids()
{
    return s_valid_ids;    
}

void PacketDatabase::init()
{
    packet_map[0x5448] = { .desc = "HTTP Response", .size = -1, .type = PacketSizeType::HTTP, .handler = nullptr };
    packet_map[0x0000] = { .desc = "Empty", .size = 2, .type = PacketSizeType::FIXED, .handler = nullptr };

    // https://github.com/OpenKore/openkore/blob/master/src/Network/Receive/ServerType0.pm
    packet_map[0x0069] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x006a] = { .desc = "Login Error", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x006b] = { .desc = "Received Characters Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x006c] = { .desc = "Login Error Game Login Server", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x006d] = { .desc = "Character Creation Successful", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x006e] = { .desc = "Character Creation Failed", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x006f] = { .desc = "Character Deletion Successful", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0070] = { .desc = "Character Deletion Failed", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0071] = { .desc = "Received Character Id And Map", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0072] = { .desc = "Received Characters", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0073] = { .desc = "Map Loaded", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0074] = { .desc = "Map Load Error", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0075] = { .desc = "Changetoingamestate", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0077] = { .desc = "Changetoingamestate", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0078] = { .desc = "Actor Exists ", .size = 54, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0079] = { .desc = "Actor Connected ", .size = 53, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x007a] = { .desc = "Changetoingamestate", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x007b] = { .desc = "Actor Moved ", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x007c] = { .desc = "Actor Spawned ", .size = 41, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x007f] = { .desc = "Received Sync", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0080] = { .desc = "Actor Died Or Disappeared", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0081] = { .desc = "Errors", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0086] = { .desc = "Actor Display", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0087] = { .desc = "Character Moves", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0088] = { .desc = "Actor Movement Interrupted", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x008a] = { .desc = "Actor Action", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x008d] = { .desc = "Public Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x008e] = { .desc = "Self Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0091] = { .desc = "Map Change", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0092] = { .desc = "Map Changed", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0095] = { .desc = "Actor Info", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0097] = { .desc = "Private Message", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0098] = { .desc = "Private Message Sent", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x009a] = { .desc = "System Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x009c] = { .desc = "Actor Look At", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x009d] = { .desc = "Item Exists", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x009e] = { .desc = "Item Appeared", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x00a0] = { .desc = "Inventory Item Added", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x00a1] = { .desc = "Item Disappeared", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00a3] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00a4] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00a5] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00a6] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00a8] = { .desc = "Use Item", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00aa] = { .desc = "Equip Item", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00ac] = { .desc = "Unequip Item", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00af] = { .desc = "Inventory Item Removed", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00b0] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00b1] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00b3] = { .desc = "Switch Character", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00b4] = { .desc = "Npc Talk", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00b5] = { .desc = "Npc Talk Continue", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00b6] = { .desc = "Npc Talk Close", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00b7] = { .desc = "Npc Talk Responses", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00bc] = { .desc = "Stats Added", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00bd] = { .desc = "Stats Info", .size = 44, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00be] = { .desc = "Stat Info", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00c0] = { .desc = "Emoticon", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00c2] = { .desc = "Users Online", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00c3] = { .desc = "Sprite Change", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00c4] = { .desc = "Npc Store Begin", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00c6] = { .desc = "Npc Store Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00c7] = { .desc = "Npc Sell List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00ca] = { .desc = "Buy Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00cb] = { .desc = "Sell Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00d1] = { .desc = "Ignore Player Result", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00d2] = { .desc = "Ignore All Result", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00d4] = { .desc = "Whisper List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x00d6] = { .desc = "Chat Created", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00d7] = { .desc = "Chat Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00d8] = { .desc = "Chat Removed", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00da] = { .desc = "Chat Join Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00db] = { .desc = "Chat Users", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00dc] = { .desc = "Chat User Join", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00dd] = { .desc = "Chat User Leave", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00df] = { .desc = "Chat Modified", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00e1] = { .desc = "Chat Newowner", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00e5] = { .desc = "Deal Request", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00e7] = { .desc = "Deal Begin", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00e9] = { .desc = "Deal Add Other", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x00ea] = { .desc = "Deal Add You", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00ec] = { .desc = "Deal Finalize", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00ee] = { .desc = "Deal Cancelled", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x00f0] = { .desc = "Deal Complete", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x00f2] = { .desc = "Storage Opened", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00f4] = { .desc = "Storage Item Added", .size = 21, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x00f6] = { .desc = "Storage Item Removed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00f8] = { .desc = "Storage Closed", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x00fa] = { .desc = "Party Organize Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00fb] = { .desc = "Party Users Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x00fd] = { .desc = "Party Invite Result", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x00fe] = { .desc = "Party Invite", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0101] = { .desc = "Party Exp", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0104] = { .desc = "Party Join", .size = 79, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0105] = { .desc = "Party Leave", .size = 31, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0106] = { .desc = "Party Hp Info", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0107] = { .desc = "Party Location", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0108] = { .desc = "Item Upgrade", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0109] = { .desc = "Party Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x010a] = { .desc = "Mvp Item", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x010b] = { .desc = "Mvp You", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x010c] = { .desc = "Mvp Other", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x010e] = { .desc = "Skill Update", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x010f] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0110] = { .desc = "Skill Use Failed", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0111] = { .desc = "Skill Add", .size = 39, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0114] = { .desc = "Skill Use", .size = 31, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0117] = { .desc = "Skill Use Location", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0119] = { .desc = "Character Status", .size = 13, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x011a] = { .desc = "Skill Used No Damage", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x011c] = { .desc = "Warp Portal List", .size = 68, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x011e] = { .desc = "Memo Success", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x011f] = { .desc = "Area Spell", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0120] = { .desc = "Area Spell Disappears", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0121] = { .desc = "Cart Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0122] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0123] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0124] = { .desc = "Cart Item Added", .size = 21, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0125] = { .desc = "Cart Item Removed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x012b] = { .desc = "Cart Off", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x012c] = { .desc = "Cart Add Failed", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x012d] = { .desc = "Shop Skill", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0131] = { .desc = "Vender Found", .size = 86, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0132] = { .desc = "Vender Lost", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0133] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0135] = { .desc = "Vender Buy Fail", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0136] = { .desc = "Vending Start", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0137] = { .desc = "Shop Sold", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0139] = { .desc = "Monster Ranged Attack", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x013a] = { .desc = "Attack Range", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x013b] = { .desc = "Arrow None", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x013c] = { .desc = "Arrow Equipped", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x013d] = { .desc = "Hp Sp Changed", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x013e] = { .desc = "Skill Cast", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0141] = { .desc = "Stat Info2", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0142] = { .desc = "Npc Talk Number", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0144] = { .desc = "Minimap Indicator", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0145] = { .desc = "Npc Image", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0147] = { .desc = "Item Skill", .size = 39, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0148] = { .desc = "Resurrection", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x014a] = { .desc = "Manner Message", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x014b] = { .desc = "Gm Silence", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x014c] = { .desc = "Guild Allies Enemy List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x014e] = { .desc = "Guild Master Member", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0150] = { .desc = "Guild Info", .size = 114, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0152] = { .desc = "Guild Emblem", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0154] = { .desc = "Guild Members List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0156] = { .desc = "Guild Update Member Position", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x015a] = { .desc = "Guild Leave", .size = 66, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x015c] = { .desc = "Guild Expulsion", .size = 90, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x015e] = { .desc = "Guild Broken", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0160] = { .desc = "Guild Member Setting List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0162] = { .desc = "Guild Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0163] = { .desc = "Guild Expulsion List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0166] = { .desc = "Guild Members Title List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0167] = { .desc = "Guild Create Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0169] = { .desc = "Guild Invite Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x016a] = { .desc = "Guild Request", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x016c] = { .desc = "Guild Name", .size = 43, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x016d] = { .desc = "Guild Member Online Status", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x016f] = { .desc = "Guild Notice", .size = 182, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0171] = { .desc = "Guild Ally Request", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0173] = { .desc = "Guild Alliance", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0174] = { .desc = "Guild Position Changed", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0177] = { .desc = "Identify List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0179] = { .desc = "Identify", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x017b] = { .desc = "Card Merge List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x017d] = { .desc = "Card Merge Status", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x017f] = { .desc = "Guild Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0181] = { .desc = "Guild Opposition Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0182] = { .desc = "Guild Member Add", .size = 106, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0184] = { .desc = "Guild Unally", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0185] = { .desc = "Guild Alliance Added", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0187] = { .desc = "Sync Request", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0188] = { .desc = "Item Upgrade", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0189] = { .desc = "No Teleport", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x018b] = { .desc = "Quit Response", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x018c] = { .desc = "Sense Result", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x018d] = { .desc = "Makable Item List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x018f] = { .desc = "Refine Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0191] = { .desc = "Talkie Box", .size = 86, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0192] = { .desc = "Map Change Cell", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0194] = { .desc = "Character Name", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0195] = { .desc = "Actor Info", .size = 102, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0196] = { .desc = "Actor Status Active", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0199] = { .desc = "Map Property", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x019a] = { .desc = "Pvp Rank", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x019b] = { .desc = "Unit Levelup", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x019e] = { .desc = "Pet Capture Process", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x01a0] = { .desc = "Pet Capture Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01a2] = { .desc = "Pet Info", .size = 37, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01a3] = { .desc = "Pet Food", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01a4] = { .desc = "Pet Info2", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01a6] = { .desc = "Egg List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x01aa] = { .desc = "Pet Emotion", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01ab] = { .desc = "Stat Info", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01ac] = { .desc = "Actor Trapped", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01ad] = { .desc = "Arrowcraft List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x01b0] = { .desc = "Monster Typechange", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01b3] = { .desc = "Npc Image", .size = 67, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01b4] = { .desc = "Guild Emblem Update", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01b5] = { .desc = "Account Payment Info", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01b6] = { .desc = "Guild Info", .size = 114, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01b9] = { .desc = "Cast Cancelled", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01c1] = { .desc = "Remain Time Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01c3] = { .desc = "Local Broadcast", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x01c4] = { .desc = "Storage Item Added", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01c5] = { .desc = "Cart Item Added", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01c8] = { .desc = "Item Used", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01c9] = { .desc = "Area Spell", .size = 97, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01cd] = { .desc = "Sage Autospell", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x01cf] = { .desc = "Devotion", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d0] = { .desc = "Revolving Entity", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d1] = { .desc = "Blade Stop", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d2] = { .desc = "Combo Delay", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d3] = { .desc = "Sound Effect", .size = 35, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d4] = { .desc = "Npc Talk Text", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d6] = { .desc = "Map Property2", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d7] = { .desc = "Sprite Change", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01d8] = { .desc = "Actor Exists", .size = 54, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01d9] = { .desc = "Actor Connected", .size = 53, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01da] = { .desc = "Actor Moved", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01dc] = { .desc = "Secure Login Key", .size = 4, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x01de] = { .desc = "Skill Use", .size = 33, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01e0] = { .desc = "Gm Req Acc Name", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01e1] = { .desc = "Revolving Entity", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01e6] = { .desc = "Marriage Partner Name", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01e9] = { .desc = "Party Join", .size = 83, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x01ea] = { .desc = "Married", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01eb] = { .desc = "Guild Location", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01ec] = { .desc = "Guild Member Map Change", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01ee] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x01ef] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x01f0] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x01f2] = { .desc = "Guild Member Online Status", .size = 20, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01f3] = { .desc = "Misc Effect", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01f4] = { .desc = "Deal Request", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01f5] = { .desc = "Deal Begin", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01f6] = { .desc = "Adopt Request", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01fc] = { .desc = "Repair List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x01fe] = { .desc = "Repair Result", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x01ff] = { .desc = "High Jump", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0201] = { .desc = "Friend List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0205] = { .desc = "Divorced", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0206] = { .desc = "Friend Logon", .size = 35, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0207] = { .desc = "Friend Request", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0209] = { .desc = "Friend Response", .size = 36, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x020a] = { .desc = "Friend Removed", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x020d] = { .desc = "Character Ban List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x020e] = { .desc = "Taekwon Packets", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x020f] = { .desc = "Pvp Point", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0215] = { .desc = "Gospel Buff Aligned", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0216] = { .desc = "Adopt Reply", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0219] = { .desc = "Top10 Blacksmith Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x021a] = { .desc = "Top10 Alchemist Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x021b] = { .desc = "Blacksmith Points", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x021c] = { .desc = "Alchemist Point", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0221] = { .desc = "Upgrade List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0223] = { .desc = "Upgrade Message", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0224] = { .desc = "Taekwon Rank", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0226] = { .desc = "Top10 Taekwon Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0227] = { .desc = "Gameguard Request", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0229] = { .desc = "Character Status", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x022a] = { .desc = "Actor Exists", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x022b] = { .desc = "Actor Connected", .size = 57, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x022c] = { .desc = "Actor Moved", .size = 64, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x022e] = { .desc = "Homunculus Property", .size = 73, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x022f] = { .desc = "Homunculus Food", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0230] = { .desc = "Homunculus Info", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0235] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0238] = { .desc = "Top10 Pk Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0239] = { .desc = "Skill Update", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x023a] = { .desc = "Storage Password Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x023c] = { .desc = "Storage Password Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x023e] = { .desc = "Storage Password Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0240] = { .desc = "Mail Refreshinbox", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0242] = { .desc = "Mail Read", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0245] = { .desc = "Mail Getattachment", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0249] = { .desc = "Mail Send", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x024a] = { .desc = "Mail New", .size = 70, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0250] = { .desc = "Auction Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0252] = { .desc = "Auction Item Request Search", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0253] = { .desc = "Starplace", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0255] = { .desc = "Mail Setattachment", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0256] = { .desc = "Auction Add Item", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0257] = { .desc = "Mail Delete", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0259] = { .desc = "Gameguard Grant", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x025a] = { .desc = "Cooking List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x025d] = { .desc = "Auction My Sell Stop", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x025f] = { .desc = "Auction Windows", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0260] = { .desc = "Mail Window", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0274] = { .desc = "Mail Return", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0276] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x027b] = { .desc = "Premium Rates Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0283] = { .desc = "Account Id", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0284] = { .desc = "Gansi Rank", .size = 284, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0287] = { .desc = "Cash Dealer", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0289] = { .desc = "Cash Buy Fail", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x028a] = { .desc = "Character Status", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0291] = { .desc = "Message String", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0293] = { .desc = "Boss Map Info", .size = 43, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0294] = { .desc = "Book Read", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0295] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0296] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0297] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0298] = { .desc = "Rental Time", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0299] = { .desc = "Rental Expired", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x029a] = { .desc = "Inventory Item Added", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x029b] = { .desc = "Mercenary Init", .size = 80, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x029d] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x02a2] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02a6] = { .desc = "Gameguard Request", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x02aa] = { .desc = "Cash Password Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02ac] = { .desc = "Cash Password Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02ad] = { .desc = "Login Pin Code Request", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02ae] = { .desc = "Initialize Message Id Encryption", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x02b1] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02b2] = { .desc = "Quest All Mission", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02b3] = { .desc = "Quest Add", .size = 17, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x02b4] = { .desc = "Quest Delete", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02b5] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02b7] = { .desc = "Quest Active", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02b8] = { .desc = "Party Show Picker", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02b9] = { .desc = "Hotkeys", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x02c1] = { .desc = "Npc Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02c5] = { .desc = "Party Invite Result", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02c6] = { .desc = "Party Invite", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02c9] = { .desc = "Party Allow Invite", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02ca] = { .desc = "Login Error Game Login Server", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02cb] = { .desc = "Instance Window Start", .size = 65, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02cc] = { .desc = "Instance Window Queue", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x02cd] = { .desc = "Instance Window Join", .size = 71, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02ce] = { .desc = "Instance Window Leave", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x02d0] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02d1] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02d2] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02d4] = { .desc = "Inventory Item Added", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x02d5] = { .desc = "Isvr Disconnect", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x02d7] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02d9] = { .desc = "Misc Config Reply", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02da] = { .desc = "Show Eq Msg Self", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02dc] = { .desc = "Battleground Message", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02dd] = { .desc = "Battleground Emblem", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02de] = { .desc = "Battleground Score", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02df] = { .desc = "Battleground Position", .size = 36, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02e0] = { .desc = "Battleground Hp", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02e1] = { .desc = "Actor Action", .size = 33, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02e7] = { .desc = "Map Property", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02e8] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02e9] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02ea] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x02eb] = { .desc = "Map Loaded", .size = 13, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02ec] = { .desc = "Actor Exists", .size = 67, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x02ed] = { .desc = "Actor Connected", .size = 59, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x02ee] = { .desc = "Actor Moved", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x02ef] = { .desc = "Font", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02f0] = { .desc = "Progress Bar", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x02f2] = { .desc = "Progress Bar Stop", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x02f7] = { .desc = "Guild Name", .size = 47, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x040c] = { .desc = "Local Broadcast", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr, .alert = true };
    packet_map[0x043d] = { .desc = "Skill Post Delay", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x043e] = { .desc = "Skill Post Delaylist", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x043f] = { .desc = "Actor Status Active", .size = 25, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0440] = { .desc = "Millenium Shield", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0441] = { .desc = "Skill Delete", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0442] = { .desc = "Sage Autospell", .size = 8, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x0444] = { .desc = "Cash Item List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0446] = { .desc = "Minimap Indicator", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0449] = { .desc = "Hack Shield Alarm", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x07d8] = { .desc = "Party Exp", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07d9] = { .desc = "Hotkeys", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x07db] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07e1] = { .desc = "Skill Update", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07e2] = { .desc = "Message String", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07e3] = { .desc = "Skill Exchange Item", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x07e6] = { .desc = "Skill Msg", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07e8] = { .desc = "Captcha Image", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x07e9] = { .desc = "Captcha Answer", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07f6] = { .desc = "Exp", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07f7] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x07f8] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x07f9] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x07fa] = { .desc = "Inventory Item Removed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07fb] = { .desc = "Skill Cast", .size = 25, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07fc] = { .desc = "Party Leader", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07fd] = { .desc = "Special Item Obtain", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x07fe] = { .desc = "Sound Effect", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x07ff] = { .desc = "Define Check", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr, .alert = true };
    packet_map[0x0800] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0803] = { .desc = "Booking Register Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0805] = { .desc = "Booking Search Request", .size = 5, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x0807] = { .desc = "Booking Delete Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0809] = { .desc = "Booking Insert", .size = 50, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x080a] = { .desc = "Booking Update", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x080b] = { .desc = "Booking Delete", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x080e] = { .desc = "Party Hp Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x080f] = { .desc = "Deal Add Other", .size = 20, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0810] = { .desc = "Open Buying Store", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0812] = { .desc = "Open Buying Store Fail", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0813] = { .desc = "Open Buying Store Item List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0814] = { .desc = "Buying Store Found", .size = 86, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0816] = { .desc = "Buying Store Lost", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0818] = { .desc = "Buying Store Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x081a] = { .desc = "Buying Buy Fail", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x081b] = { .desc = "Buying Store Update", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x081c] = { .desc = "Buying Store Item Delete", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x081d] = { .desc = "Elemental Info", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x081e] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0824] = { .desc = "Buying Store Fail", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0828] = { .desc = "Char Delete2 Result", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x082a] = { .desc = "Char Delete2 Accept Result", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x082c] = { .desc = "Char Delete2 Cancel Result", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x082d] = { .desc = "Received Characters Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0836] = { .desc = "Search Store Result", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0837] = { .desc = "Search Store Fail", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0839] = { .desc = "Guild Expulsion", .size = 66, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x083a] = { .desc = "Search Store Open", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x083d] = { .desc = "Search Store Pos", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x083e] = { .desc = "Login Error", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0845] = { .desc = "Cash Shop Open Result", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0849] = { .desc = "Cash Shop Buy Result", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x084b] = { .desc = "Item Appeared", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0856] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0857] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0858] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0859] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0871] = { .desc = "Unknown", .size = 2, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08b3] = { .desc = "Show Script", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x08b4] = { .desc = "Pet Capture Process", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x08b6] = { .desc = "Pet Capture Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08b9] = { .desc = "Login Pin Code Request", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08bb] = { .desc = "Login Pin New Code Result", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08c7] = { .desc = "Area Spell", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x08c8] = { .desc = "Actor Action", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08ca] = { .desc = "Cash Shop List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x08cb] = { .desc = "Rates Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x08cd] = { .desc = "Actor Movement Interrupted", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08cf] = { .desc = "Revolving Entity", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08d2] = { .desc = "High Jump", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08e2] = { .desc = "Navigate To", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x08fe] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x08ff] = { .desc = "Actor Status Active", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0900] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0901] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0902] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0903] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0906] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0908] = { .desc = "Inventory Item Favorite", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x090f] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0914] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0915] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x096d] = { .desc = "Merge Item Open", .size = 4, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x096f] = { .desc = "Merge Item Result", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0975] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0976] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0977] = { .desc = "Monster Hp Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x097a] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x097b] = { .desc = "Rates Info2", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x097d] = { .desc = "Top10", .size = 4, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x097e] = { .desc = "Rank Points", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0983] = { .desc = "Actor Status Active", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0984] = { .desc = "Actor Status Active", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0985] = { .desc = "Skill Post Delaylist", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0988] = { .desc = "Clan User", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x098a] = { .desc = "Clan Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x098d] = { .desc = "Clan Leave", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x098e] = { .desc = "Clan Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0990] = { .desc = "Inventory Item Added", .size = 31, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0991] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0992] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0993] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0994] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0995] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0996] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0997] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0999] = { .desc = "Equip Item", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x099a] = { .desc = "Unequip Item", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x099b] = { .desc = "Map Property3", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x099d] = { .desc = "Received Characters", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x099f] = { .desc = "Area Spell Multiple2", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09a0] = { .desc = "Sync Received Characters", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09a6] = { .desc = "Banking Check", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09a8] = { .desc = "Banking Deposit", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09aa] = { .desc = "Banking Withdraw", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09bb] = { .desc = "Storage Opened", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09bf] = { .desc = "Storage Closed", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x09ca] = { .desc = "Area Spell Multiple3", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09cb] = { .desc = "Skill Used No Damage", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09cd] = { .desc = "Message String", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09cf] = { .desc = "Gameguard Request", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09d1] = { .desc = "Progress Bar Unit", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09d5] = { .desc = "Npc Market Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09d7] = { .desc = "Npc Market Purchase Result", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09da] = { .desc = "Guild Storage Log", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09db] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09dc] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09dd] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09de] = { .desc = "Private Message", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09df] = { .desc = "Private Message Sent", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09e5] = { .desc = "Shop Sold Long", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09e7] = { .desc = "Unread Rodex", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09eb] = { .desc = "Rodex Read Mail", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09ed] = { .desc = "Rodex Write Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09f0] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09f2] = { .desc = "Rodex Get Zeny", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09f4] = { .desc = "Rodex Get Item", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09f6] = { .desc = "Rodex Delete", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09f7] = { .desc = "Homunculus Property", .size = 77, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x09f8] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09f9] = { .desc = "Quest Add", .size = 17, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x09fa] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09fc] = { .desc = "Pet Evolution Result", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr, .alert = true };
    packet_map[0x09fd] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09fe] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x09ff] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a00] = { .desc = "Hotkeys", .size = 3, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x0a05] = { .desc = "Rodex Add Item", .size = 53, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a07] = { .desc = "Rodex Remove Item", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a09] = { .desc = "Deal Add Other", .size = 45, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a0a] = { .desc = "Storage Item Added", .size = 47, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a0b] = { .desc = "Cart Item Added", .size = 47, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a0c] = { .desc = "Inventory Item Added", .size = 56, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a0d] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a0f] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a10] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a12] = { .desc = "Rodex Open Write", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a14] = { .desc = "Rodex Check Player", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a15] = { .desc = "Gold Pc Cafe Point", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a17] = { .desc = "Dynamicnpc Create Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a18] = { .desc = "Map Loaded", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a1a] = { .desc = "Roulette Window", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a1c] = { .desc = "Roulette Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a20] = { .desc = "Roulette Window Update", .size = 21, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a22] = { .desc = "Roulette Recv Item", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a23] = { .desc = "Achievement List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a24] = { .desc = "Achievement Update", .size = 66, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a26] = { .desc = "Achievement Reward Ack", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a27] = { .desc = "Hp Sp Changed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a28] = { .desc = "Open Store Status", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a2d] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a2f] = { .desc = "Change Title", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a30] = { .desc = "Actor Info", .size = 106, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a34] = { .desc = "Senbei Amount", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a36] = { .desc = "Monster Hp Info Tiny", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a37] = { .desc = "Inventory Item Added", .size = 69, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a38] = { .desc = "Open Ui", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a3b] = { .desc = "Hat Effect", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a43] = { .desc = "Party Join", .size = 85, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a44] = { .desc = "Party Users Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a47] = { .desc = "Stylist Res", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a4a] = { .desc = "Private Airship Type", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a4b] = { .desc = "Map Change", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a4c] = { .desc = "Map Changed", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a51] = { .desc = "Rodex Check Player", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a53] = { .desc = "Captcha Upload Request", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a55] = { .desc = "Captcha Upload Request Status", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0a57] = { .desc = "Macro Reporter Status", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a58] = { .desc = "Macro Detector", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a59] = { .desc = "Macro Detector Image", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a5b] = { .desc = "Macro Detector Show", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a5d] = { .desc = "Macro Detector Status", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a6a] = { .desc = "Captcha Preview", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a6b] = { .desc = "Captcha Preview Image", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a6d] = { .desc = "Macro Reporter Select", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a6f] = { .desc = "Message String", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a7b] = { .desc = "Eac Key", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[0x0a7d] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a82] = { .desc = "Guild Expulsion", .size = 46, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a83] = { .desc = "Guild Leave", .size = 46, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a84] = { .desc = "Guild Info", .size = 94, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a89] = { .desc = "Offline Clone Found", .size = 57, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a8a] = { .desc = "Offline Clone Lost", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a8d] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a91] = { .desc = "Buying Store Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a95] = { .desc = "Misc Config", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a96] = { .desc = "Deal Add Other", .size = 61, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a98] = { .desc = "Equip Item Switch", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0a9a] = { .desc = "Unequip Item Switch", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0a9b] = { .desc = "Equip Switch Log", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0a9d] = { .desc = "Equip Switch Run Res", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0aa0] = { .desc = "Refineui Opene", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0aa2] = { .desc = "Refineui Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0aa5] = { .desc = "Guild Members List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0aa8] = { .desc = "Misc Config", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ab2] = { .desc = "Party Dead", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ab8] = { .desc = "Move Interrupt", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0ab9] = { .desc = "Item Preview", .size = 39, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0abd] = { .desc = "Partylv Info", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0abe] = { .desc = "Warp Portal List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0ac2] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0ac4] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0ac5] = { .desc = "Received Character Id And Map", .size = 156, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ac7] = { .desc = "Map Changed", .size = 156, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ac9] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0aca] = { .desc = "Errors", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0acb] = { .desc = "Stat Info", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0acc] = { .desc = "Exp", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0acd] = { .desc = "Login Error", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ada] = { .desc = "Refine Status", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0adc] = { .desc = "Misc Config", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0add] = { .desc = "Item Appeared", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ade] = { .desc = "Overweight Percent", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0adf] = { .desc = "Actor Info", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ae0] = { .desc = "Login Error", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ae2] = { .desc = "Open Ui", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ae3] = { .desc = "Received Login Token", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0ae4] = { .desc = "Party Join", .size = 89, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0ae5] = { .desc = "Party Users Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0af0] = { .desc = "Action Ui", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[0x0af7] = { .desc = "Character Name", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0afb] = { .desc = "Sage Autospell", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0afd] = { .desc = "Guild Position", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0afe] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0aff] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b03] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b05] = { .desc = "Offline Clone Found", .size = 63, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b08] = { .desc = "Item List Start", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b09] = { .desc = "Item List Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b0a] = { .desc = "Item List Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b0b] = { .desc = "Item List End", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b0c] = { .desc = "Quest Add", .size = 155, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b13] = { .desc = "Item Preview", .size = 48, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b18] = { .desc = "Inventory Expansion Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b1a] = { .desc = "Skill Cast", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b1b] = { .desc = "Load Confirm", .size = 2, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b1d] = { .desc = "Ping", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[0x0b20] = { .desc = "Hotkeys", .size = 271, .type = PacketSizeType::FIXED, .handler = nullptr};
    packet_map[0x0b2f] = { .desc = "Homunculus Property", .size = 73, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b31] = { .desc = "Skill Add", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b32] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b33] = { .desc = "Skill Update", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b39] = { .desc = "Item List Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b3d] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b41] = { .desc = "Inventory Item Added", .size = 70, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b44] = { .desc = "Storage Item Added", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b45] = { .desc = "Cart Item Added", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b47] = { .desc = "Char Emblem Update", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b4d] = { .desc = "Unknown", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b5f] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b60] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b6f] = { .desc = "Character Creation Successful", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[0x0b72] = { .desc = "Received Characters", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b73] = { .desc = "Revolving Entity", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b76] = { .desc = "Homunculus Property", .size = 77, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b77] = { .desc = "Npc Store Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b7b] = { .desc = "Guild Info", .size = 118, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b7c] = { .desc = "Guild Expulsion List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b7d] = { .desc = "Guild Members List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0b7e] = { .desc = "Guild Member Add", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[0x0b8d] = { .desc = "Repute Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[0x0ba4] = { .desc = "Homunculus Property", .size = 85, .type = PacketSizeType::FIXED, .handler = nullptr };
    
    for (const auto& [id, _] : packet_map)
        s_valid_ids.insert(id);
}
