#include "../../public/packets/PacketDatabase.h"

#include "../../public/packets/PackeTable.h"

PacketDatabase::PacketDatabase() {
    init();
}

PacketDatabase& PacketDatabase::instance()
{
    static PacketDatabase db;
    return db;
}

const packet_detail* PacketDatabase::get(const PacketInfo& head)
{
    const auto& map = instance().packet_map;
    const auto it = map.find(head);
    if (it != map.end()) {
        return &it->second;
    }
    return nullptr;
}

void PacketDatabase::init()
{
    packet_map[PacketInfo::HTTP_RESPONSE] = { .desc = "HTTP Response", .size = -1, .type = PacketSizeType::HTTP, .handler = nullptr };
    packet_map[PacketInfo::EMPTY] = { .desc = "Empty", .size = 2, .type = PacketSizeType::FIXED, .handler = nullptr };

    // https://github.com/OpenKore/openkore/blob/master/src/Network/Receive/ServerType0.pm
    packet_map[PacketInfo::ACCOUNT_SERVER_INFO_0] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_ERROR_0] = { .desc = "Login Error", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RECEIVED_CHARACTERS_INFO_0] = { .desc = "Received Characters Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_ERROR_GAME_LOGIN_SERVER_0] = { .desc = "Login Error Game Login Server", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CHARACTER_CREATION_SUCCESSFUL_0] = { .desc = "Character Creation Successful", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CHARACTER_CREATION_FAILED] = { .desc = "Character Creation Failed", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHARACTER_DELETION_SUCCESSFUL] = { .desc = "Character Deletion Successful", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CHARACTER_DELETION_FAILED] = { .desc = "Character Deletion Failed", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::RECEIVED_CHARACTER_ID_AND_MAP_0] = { .desc = "Received Character Id And Map", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RECEIVED_CHARACTERS_0] = { .desc = "Received Characters", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MAP_LOADED_0] = { .desc = "Map Loaded", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_LOAD_ERROR] = { .desc = "Map Load Error", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHANGETOINGAMESTATE_0] = { .desc = "Changetoingamestate", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::CHANGETOINGAMESTATE_1] = { .desc = "Changetoingamestate", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_EXISTS_0] = { .desc = "Actor Exists ", .size = 54, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_CONNECTED_0] = { .desc = "Actor Connected ", .size = 53, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHANGETOINGAMESTATE_2] = { .desc = "Changetoingamestate", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_MOVED_0] = { .desc = "Actor Moved ", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_SPAWNED] = { .desc = "Actor Spawned ", .size = 41, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::RECEIVED_SYNC] = { .desc = "Received Sync", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_DIED_OR_DISAPPEARED] = { .desc = "Actor Died Or Disappeared", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ERRORS_0] = { .desc = "Errors", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_DISPLAY] = { .desc = "Actor Display", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHARACTER_MOVES] = { .desc = "Character Moves", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_MOVEMENT_INTERRUPTED_0] = { .desc = "Actor Movement Interrupted", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_ACTION_0] = { .desc = "Actor Action", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PUBLIC_CHAT] = { .desc = "Public Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SELF_CHAT] = { .desc = "Self Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MAP_CHANGE_0] = { .desc = "Map Change", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_CHANGED_0] = { .desc = "Map Changed", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_INFO_0] = { .desc = "Actor Info", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PRIVATE_MESSAGE_0] = { .desc = "Private Message", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PRIVATE_MESSAGE_SENT_0] = { .desc = "Private Message Sent", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SYSTEM_CHAT] = { .desc = "System Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_LOOK_AT] = { .desc = "Actor Look At", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_EXISTS] = { .desc = "Item Exists", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_APPEARED_0] = { .desc = "Item Appeared", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::INVENTORY_ITEM_ADDED_0] = { .desc = "Inventory Item Added", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ITEM_DISAPPEARED] = { .desc = "Item Disappeared", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_STACKABLE_0] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_NONSTACKABLE_0] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_STACKABLE_0] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_NONSTACKABLE_0] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::USE_ITEM] = { .desc = "Use Item", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::EQUIP_ITEM_0] = { .desc = "Equip Item", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::UNEQUIP_ITEM_0] = { .desc = "Unequip Item", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEM_REMOVED_0] = { .desc = "Inventory Item Removed", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO_0] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO_1] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SWITCH_CHARACTER] = { .desc = "Switch Character", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_TALK] = { .desc = "Npc Talk", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::NPC_TALK_CONTINUE] = { .desc = "Npc Talk Continue", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_TALK_CLOSE] = { .desc = "Npc Talk Close", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_TALK_RESPONSES] = { .desc = "Npc Talk Responses", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STATS_ADDED] = { .desc = "Stats Added", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STATS_INFO] = { .desc = "Stats Info", .size = 44, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO_2] = { .desc = "Stat Info", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::EMOTICON] = { .desc = "Emoticon", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::USERS_ONLINE] = { .desc = "Users Online", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SPRITE_CHANGE_0] = { .desc = "Sprite Change", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_STORE_BEGIN] = { .desc = "Npc Store Begin", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_STORE_INFO_0] = { .desc = "Npc Store Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::NPC_SELL_LIST] = { .desc = "Npc Sell List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::BUY_RESULT] = { .desc = "Buy Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SELL_RESULT] = { .desc = "Sell Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::IGNORE_PLAYER_RESULT] = { .desc = "Ignore Player Result", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::IGNORE_ALL_RESULT] = { .desc = "Ignore All Result", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::WHISPER_LIST] = { .desc = "Whisper List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::CHAT_CREATED] = { .desc = "Chat Created", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAT_INFO] = { .desc = "Chat Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CHAT_REMOVED] = { .desc = "Chat Removed", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAT_JOIN_RESULT] = { .desc = "Chat Join Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAT_USERS] = { .desc = "Chat Users", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CHAT_USER_JOIN] = { .desc = "Chat User Join", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAT_USER_LEAVE] = { .desc = "Chat User Leave", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAT_MODIFIED] = { .desc = "Chat Modified", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CHAT_NEWOWNER] = { .desc = "Chat Newowner", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_REQUEST_0] = { .desc = "Deal Request", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_BEGIN_0] = { .desc = "Deal Begin", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_ADD_OTHER_0] = { .desc = "Deal Add Other", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::DEAL_ADD_YOU] = { .desc = "Deal Add You", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_FINALIZE] = { .desc = "Deal Finalize", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_CANCELLED] = { .desc = "Deal Cancelled", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::DEAL_COMPLETE] = { .desc = "Deal Complete", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::STORAGE_OPENED_0] = { .desc = "Storage Opened", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEM_ADDED_0] = { .desc = "Storage Item Added", .size = 21, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::STORAGE_ITEM_REMOVED] = { .desc = "Storage Item Removed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_CLOSED_0] = { .desc = "Storage Closed", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::PARTY_ORGANIZE_RESULT] = { .desc = "Party Organize Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_USERS_INFO_0] = { .desc = "Party Users Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PARTY_INVITE_RESULT_0] = { .desc = "Party Invite Result", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_INVITE_0] = { .desc = "Party Invite", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_EXP_0] = { .desc = "Party Exp", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_JOIN_0] = { .desc = "Party Join", .size = 79, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_LEAVE] = { .desc = "Party Leave", .size = 31, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_HP_INFO_0] = { .desc = "Party Hp Info", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_LOCATION] = { .desc = "Party Location", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_UPGRADE_0] = { .desc = "Item Upgrade", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::PARTY_CHAT] = { .desc = "Party Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MVP_ITEM] = { .desc = "Mvp Item", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MVP_YOU] = { .desc = "Mvp You", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MVP_OTHER] = { .desc = "Mvp Other", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_UPDATE_0] = { .desc = "Skill Update", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILLS_LIST_0] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::SKILL_USE_FAILED] = { .desc = "Skill Use Failed", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_ADD_0] = { .desc = "Skill Add", .size = 39, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_USE_0] = { .desc = "Skill Use", .size = 31, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_USE_LOCATION] = { .desc = "Skill Use Location", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHARACTER_STATUS_0] = { .desc = "Character Status", .size = 13, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_USED_NO_DAMAGE_0] = { .desc = "Skill Used No Damage", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::WARP_PORTAL_LIST_0] = { .desc = "Warp Portal List", .size = 68, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MEMO_SUCCESS] = { .desc = "Memo Success", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AREA_SPELL_0] = { .desc = "Area Spell", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AREA_SPELL_DISAPPEARS] = { .desc = "Area Spell Disappears", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CART_INFO] = { .desc = "Cart Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_NONSTACKABLE_0] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_STACKABLE_0] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEM_ADDED_0] = { .desc = "Cart Item Added", .size = 21, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CART_ITEM_REMOVED] = { .desc = "Cart Item Removed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CART_OFF] = { .desc = "Cart Off", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CART_ADD_FAILED] = { .desc = "Cart Add Failed", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SHOP_SKILL] = { .desc = "Shop Skill", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::VENDER_FOUND] = { .desc = "Vender Found", .size = 86, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::VENDER_LOST] = { .desc = "Vender Lost", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::VENDER_ITEMS_LIST_0] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::VENDER_BUY_FAIL] = { .desc = "Vender Buy Fail", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::VENDING_START] = { .desc = "Vending Start", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SHOP_SOLD] = { .desc = "Shop Sold", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MONSTER_RANGED_ATTACK] = { .desc = "Monster Ranged Attack", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ATTACK_RANGE] = { .desc = "Attack Range", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ARROW_NONE] = { .desc = "Arrow None", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ARROW_EQUIPPED] = { .desc = "Arrow Equipped", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HP_SP_CHANGED_0] = { .desc = "Hp Sp Changed", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_CAST_0] = { .desc = "Skill Cast", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO2] = { .desc = "Stat Info2", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_TALK_NUMBER] = { .desc = "Npc Talk Number", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MINIMAP_INDICATOR_0] = { .desc = "Minimap Indicator", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_IMAGE_0] = { .desc = "Npc Image", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_SKILL] = { .desc = "Item Skill", .size = 39, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RESURRECTION] = { .desc = "Resurrection", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MANNER_MESSAGE] = { .desc = "Manner Message", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GM_SILENCE] = { .desc = "Gm Silence", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_ALLIES_ENEMY_LIST] = { .desc = "Guild Allies Enemy List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MASTER_MEMBER] = { .desc = "Guild Master Member", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_INFO_0] = { .desc = "Guild Info", .size = 114, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::GUILD_EMBLEM] = { .desc = "Guild Emblem", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBERS_LIST_0] = { .desc = "Guild Members List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_UPDATE_MEMBER_POSITION] = { .desc = "Guild Update Member Position", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_LEAVE_0] = { .desc = "Guild Leave", .size = 66, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_EXPULSION_0] = { .desc = "Guild Expulsion", .size = 90, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_BROKEN] = { .desc = "Guild Broken", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBER_SETTING_LIST] = { .desc = "Guild Member Setting List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::GUILD_SKILLS_LIST] = { .desc = "Guild Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::GUILD_EXPULSION_LIST_0] = { .desc = "Guild Expulsion List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBERS_TITLE_LIST] = { .desc = "Guild Members Title List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::GUILD_CREATE_RESULT] = { .desc = "Guild Create Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_INVITE_RESULT] = { .desc = "Guild Invite Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_REQUEST] = { .desc = "Guild Request", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_NAME_0] = { .desc = "Guild Name", .size = 43, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBER_ONLINE_STATUS_0] = { .desc = "Guild Member Online Status", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_NOTICE] = { .desc = "Guild Notice", .size = 182, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_ALLY_REQUEST] = { .desc = "Guild Ally Request", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_ALLIANCE] = { .desc = "Guild Alliance", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_POSITION_CHANGED] = { .desc = "Guild Position Changed", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::IDENTIFY_LIST] = { .desc = "Identify List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::IDENTIFY] = { .desc = "Identify", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CARD_MERGE_LIST] = { .desc = "Card Merge List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::CARD_MERGE_STATUS] = { .desc = "Card Merge Status", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_CHAT] = { .desc = "Guild Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_OPPOSITION_RESULT] = { .desc = "Guild Opposition Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBER_ADD_0] = { .desc = "Guild Member Add", .size = 106, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_UNALLY] = { .desc = "Guild Unally", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_ALLIANCE_ADDED] = { .desc = "Guild Alliance Added", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SYNC_REQUEST] = { .desc = "Sync Request", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_UPGRADE_1] = { .desc = "Item Upgrade", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NO_TELEPORT] = { .desc = "No Teleport", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::QUIT_RESPONSE] = { .desc = "Quit Response", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SENSE_RESULT] = { .desc = "Sense Result", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAKABLE_ITEM_LIST] = { .desc = "Makable Item List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::REFINE_RESULT] = { .desc = "Refine Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::TALKIE_BOX] = { .desc = "Talkie Box", .size = 86, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_CHANGE_CELL] = { .desc = "Map Change Cell", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHARACTER_NAME_0] = { .desc = "Character Name", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_INFO_1] = { .desc = "Actor Info", .size = 102, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_STATUS_ACTIVE_0] = { .desc = "Actor Status Active", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_PROPERTY_0] = { .desc = "Map Property", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PVP_RANK] = { .desc = "Pvp Rank", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::UNIT_LEVELUP] = { .desc = "Unit Levelup", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PET_CAPTURE_PROCESS_0] = { .desc = "Pet Capture Process", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::PET_CAPTURE_RESULT_0] = { .desc = "Pet Capture Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PET_INFO] = { .desc = "Pet Info", .size = 37, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PET_FOOD] = { .desc = "Pet Food", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::PET_INFO2] = { .desc = "Pet Info2", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::EGG_LIST] = { .desc = "Egg List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::PET_EMOTION] = { .desc = "Pet Emotion", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO_3] = { .desc = "Stat Info", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_TRAPPED] = { .desc = "Actor Trapped", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ARROWCRAFT_LIST] = { .desc = "Arrowcraft List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::MONSTER_TYPECHANGE] = { .desc = "Monster Typechange", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_IMAGE_1] = { .desc = "Npc Image", .size = 67, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_EMBLEM_UPDATE] = { .desc = "Guild Emblem Update", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACCOUNT_PAYMENT_INFO] = { .desc = "Account Payment Info", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::GUILD_INFO_1] = { .desc = "Guild Info", .size = 114, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CAST_CANCELLED] = { .desc = "Cast Cancelled", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REMAIN_TIME_INFO] = { .desc = "Remain Time Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOCAL_BROADCAST_1] = { .desc = "Local Broadcast", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEM_ADDED_1] = { .desc = "Storage Item Added", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CART_ITEM_ADDED_1] = { .desc = "Cart Item Added", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ITEM_USED] = { .desc = "Item Used", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AREA_SPELL_1] = { .desc = "Area Spell", .size = 97, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SAGE_AUTOSPELL_0] = { .desc = "Sage Autospell", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::DEVOTION] = { .desc = "Devotion", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REVOLVING_ENTITY_0] = { .desc = "Revolving Entity", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BLADE_STOP] = { .desc = "Blade Stop", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::COMBO_DELAY] = { .desc = "Combo Delay", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SOUND_EFFECT_0] = { .desc = "Sound Effect", .size = 35, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_TALK_TEXT] = { .desc = "Npc Talk Text", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_PROPERTY_2] = { .desc = "Map Property2", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SPRITE_CHANGE_1] = { .desc = "Sprite Change", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_1] = { .desc = "Actor Exists", .size = 54, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_CONNECTED_1] = { .desc = "Actor Connected", .size = 53, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_MOVED_1] = { .desc = "Actor Moved", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::SECURE_LOGIN_KEY] = { .desc = "Secure Login Key", .size = 4, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::SKILL_USE_1] = { .desc = "Skill Use", .size = 33, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GM_REQ_ACC_NAME] = { .desc = "Gm Req Acc Name", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REVOLVING_ENTITY_1] = { .desc = "Revolving Entity", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MARRIAGE_PARTNER_NAME] = { .desc = "Marriage Partner Name", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_JOIN_1] = { .desc = "Party Join", .size = 83, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MARRIED] = { .desc = "Married", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_LOCATION] = { .desc = "Guild Location", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBER_MAP_CHANGE] = { .desc = "Guild Member Map Change", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_STACKABLE_1] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_STACKABLE_1] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_STACKABLE_1] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBER_ONLINE_STATUS_1] = { .desc = "Guild Member Online Status", .size = 20, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MISC_EFFECT] = { .desc = "Misc Effect", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_REQUEST_1] = { .desc = "Deal Request", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_BEGIN_1] = { .desc = "Deal Begin", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ADOPT_REQUEST] = { .desc = "Adopt Request", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REPAIR_LIST] = { .desc = "Repair List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::REPAIR_RESULT] = { .desc = "Repair Result", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HIGH_JUMP_0] = { .desc = "High Jump", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::FRIEND_LIST] = { .desc = "Friend List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::DIVORCED] = { .desc = "Divorced", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::FRIEND_LOGON] = { .desc = "Friend Logon", .size = 35, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::FRIEND_REQUEST] = { .desc = "Friend Request", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::FRIEND_RESPONSE] = { .desc = "Friend Response", .size = 36, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::FRIEND_REMOVED] = { .desc = "Friend Removed", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHARACTER_BAN_LIST] = { .desc = "Character Ban List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::TAEKWON_PACKETS] = { .desc = "Taekwon Packets", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PVP_POINT] = { .desc = "Pvp Point", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::GOSPEL_BUFF_ALIGNED] = { .desc = "Gospel Buff Aligned", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ADOPT_REPLY] = { .desc = "Adopt Reply", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::TOP10_BLACKSMITH_RANK] = { .desc = "Top10 Blacksmith Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::TOP10_ALCHEMIST_RANK] = { .desc = "Top10 Alchemist Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::BLACKSMITH_POINTS] = { .desc = "Blacksmith Points", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ALCHEMIST_POINT] = { .desc = "Alchemist Point", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::UPGRADE_LIST] = { .desc = "Upgrade List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::UPGRADE_MESSAGE] = { .desc = "Upgrade Message", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::TAEKWON_RANK] = { .desc = "Taekwon Rank", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::TOP10_TAEKWON_RANK] = { .desc = "Top10 Taekwon Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::GAMEGUARD_REQUEST_0] = { .desc = "Gameguard Request", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CHARACTER_STATUS_1] = { .desc = "Character Status", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_2] = { .desc = "Actor Exists", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_CONNECTED_2] = { .desc = "Actor Connected", .size = 57, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_MOVED_2] = { .desc = "Actor Moved", .size = 64, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::HOMUNCULUS_PROPERTY_0] = { .desc = "Homunculus Property", .size = 73, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HOMUNCULUS_FOOD] = { .desc = "Homunculus Food", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HOMUNCULUS_INFO] = { .desc = "Homunculus Info", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILLS_LIST_1] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::TOP10_PK_RANK] = { .desc = "Top10 Pk Rank", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::SKILL_UPDATE_1] = { .desc = "Skill Update", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_PASSWORD_REQUEST_0] = { .desc = "Storage Password Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_PASSWORD_RESULT] = { .desc = "Storage Password Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_PASSWORD_REQUEST_1] = { .desc = "Storage Password Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MAIL_REFRESHINBOX] = { .desc = "Mail Refreshinbox", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MAIL_READ] = { .desc = "Mail Read", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MAIL_GETATTACHMENT] = { .desc = "Mail Getattachment", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAIL_SEND] = { .desc = "Mail Send", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAIL_NEW] = { .desc = "Mail New", .size = 70, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AUCTION_RESULT] = { .desc = "Auction Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AUCTION_ITEM_REQUEST_SEARCH] = { .desc = "Auction Item Request Search", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::STARPLACE] = { .desc = "Starplace", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAIL_SETATTACHMENT] = { .desc = "Mail Setattachment", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AUCTION_ADD_ITEM] = { .desc = "Auction Add Item", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAIL_DELETE] = { .desc = "Mail Delete", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GAMEGUARD_GRANT] = { .desc = "Gameguard Grant", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::COOKING_LIST] = { .desc = "Cooking List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::AUCTION_MY_SELL_STOP] = { .desc = "Auction My Sell Stop", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AUCTION_WINDOWS] = { .desc = "Auction Windows", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MAIL_WINDOW] = { .desc = "Mail Window", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MAIL_RETURN] = { .desc = "Mail Return", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACCOUNT_SERVER_INFO_1] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PREMIUM_RATES_INFO] = { .desc = "Premium Rates Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACCOUNT_ID] = { .desc = "Account Id", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GANSI_RANK] = { .desc = "Gansi Rank", .size = 284, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CASH_DEALER] = { .desc = "Cash Dealer", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CASH_BUY_FAIL] = { .desc = "Cash Buy Fail", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CHARACTER_STATUS_2] = { .desc = "Character Status", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MESSAGE_STRING_0] = { .desc = "Message String", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BOSS_MAP_INFO] = { .desc = "Boss Map Info", .size = 43, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::BOOK_READ] = { .desc = "Book Read", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_NONSTACKABLE_1] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_NONSTACKABLE_1] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_NONSTACKABLE_1] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RENTAL_TIME] = { .desc = "Rental Time", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::RENTAL_EXPIRED] = { .desc = "Rental Expired", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::INVENTORY_ITEM_ADDED_1] = { .desc = "Inventory Item Added", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MERCENARY_INIT] = { .desc = "Mercenary Init", .size = 80, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILLS_LIST_2] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO_4] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GAMEGUARD_REQUEST_1] = { .desc = "Gameguard Request", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::CASH_PASSWORD_REQUEST] = { .desc = "Cash Password Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CASH_PASSWORD_RESULT] = { .desc = "Cash Password Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_PIN_CODE_REQUEST_0] = { .desc = "Login Pin Code Request", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INITIALIZE_MESSAGE_ID_ENCRYPTION] = { .desc = "Initialize Message Id Encryption", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::QUEST_ALL_LIST_0] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ALL_MISSION] = { .desc = "Quest All Mission", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ADD_0] = { .desc = "Quest Add", .size = 17, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::QUEST_DELETE] = { .desc = "Quest Delete", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::QUEST_UPDATE_MISSION_HUNT_0] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ACTIVE] = { .desc = "Quest Active", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_SHOW_PICKER] = { .desc = "Party Show Picker", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HOTKEYS_0] = { .desc = "Hotkeys", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::NPC_CHAT] = { .desc = "Npc Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PARTY_INVITE_RESULT_1] = { .desc = "Party Invite Result", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_INVITE_1] = { .desc = "Party Invite", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_ALLOW_INVITE] = { .desc = "Party Allow Invite", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_ERROR_GAME_LOGIN_SERVER_1] = { .desc = "Login Error Game Login Server", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INSTANCE_WINDOW_START] = { .desc = "Instance Window Start", .size = 65, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INSTANCE_WINDOW_QUEUE] = { .desc = "Instance Window Queue", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::INSTANCE_WINDOW_JOIN] = { .desc = "Instance Window Join", .size = 71, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INSTANCE_WINDOW_LEAVE] = { .desc = "Instance Window Leave", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::INVENTORY_ITEMS_NONSTACKABLE_2] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_NONSTACKABLE_2] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_NONSTACKABLE_2] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEM_ADDED_2] = { .desc = "Inventory Item Added", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ISVR_DISCONNECT] = { .desc = "Isvr Disconnect", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::SHOW_EQ_0] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MISC_CONFIG_REPLY] = { .desc = "Misc Config Reply", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SHOW_EQ_MSG_SELF] = { .desc = "Show Eq Msg Self", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BATTLEGROUND_MESSAGE] = { .desc = "Battleground Message", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::BATTLEGROUND_EMBLEM] = { .desc = "Battleground Emblem", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BATTLEGROUND_SCORE] = { .desc = "Battleground Score", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BATTLEGROUND_POSITION] = { .desc = "Battleground Position", .size = 36, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BATTLEGROUND_HP] = { .desc = "Battleground Hp", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_ACTION_1] = { .desc = "Actor Action", .size = 33, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_PROPERTY_1] = { .desc = "Map Property", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_STACKABLE_2] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_STACKABLE_2] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_STACKABLE_2] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MAP_LOADED_1] = { .desc = "Map Loaded", .size = 13, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_3] = { .desc = "Actor Exists", .size = 67, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_CONNECTED_3] = { .desc = "Actor Connected", .size = 59, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_MOVED_3] = { .desc = "Actor Moved", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::FONT] = { .desc = "Font", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PROGRESS_BAR] = { .desc = "Progress Bar", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PROGRESS_BAR_STOP] = { .desc = "Progress Bar Stop", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::GUILD_NAME_1] = { .desc = "Guild Name", .size = 47, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::LOCAL_BROADCAST_0] = { .desc = "Local Broadcast", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::SKILL_POST_DELAY] = { .desc = "Skill Post Delay", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_POST_DELAYLIST_0] = { .desc = "Skill Post Delaylist", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_STATUS_ACTIVE_1] = { .desc = "Actor Status Active", .size = 25, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MILLENIUM_SHIELD] = { .desc = "Millenium Shield", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_DELETE] = { .desc = "Skill Delete", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SAGE_AUTOSPELL_1] = { .desc = "Sage Autospell", .size = 8, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CASH_ITEM_LIST] = { .desc = "Cash Item List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MINIMAP_INDICATOR_1] = { .desc = "Minimap Indicator", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HACK_SHIELD_ALARM] = { .desc = "Hack Shield Alarm", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::PARTY_EXP_1] = { .desc = "Party Exp", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HOTKEYS_1] = { .desc = "Hotkeys", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::STAT_INFO_5] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_UPDATE_2] = { .desc = "Skill Update", .size = 15, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MESSAGE_STRING_1] = { .desc = "Message String", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_EXCHANGE_ITEM] = { .desc = "Skill Exchange Item", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::SKILL_MSG] = { .desc = "Skill Msg", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CAPTCHA_IMAGE] = { .desc = "Captcha Image", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CAPTCHA_ANSWER] = { .desc = "Captcha Answer", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::EXP_0] = { .desc = "Exp", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_4] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_CONNECTED_4] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_MOVED_4] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEM_REMOVED_1] = { .desc = "Inventory Item Removed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_CAST_1] = { .desc = "Skill Cast", .size = 25, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_LEADER] = { .desc = "Party Leader", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SPECIAL_ITEM_OBTAIN] = { .desc = "Special Item Obtain", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SOUND_EFFECT_1] = { .desc = "Sound Effect", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEFINE_CHECK] = { .desc = "Define Check", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::VENDER_ITEMS_LIST_1] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::BOOKING_REGISTER_REQUEST] = { .desc = "Booking Register Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BOOKING_SEARCH_REQUEST] = { .desc = "Booking Search Request", .size = 5, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::BOOKING_DELETE_REQUEST] = { .desc = "Booking Delete Request", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BOOKING_INSERT] = { .desc = "Booking Insert", .size = 50, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BOOKING_UPDATE] = { .desc = "Booking Update", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BOOKING_DELETE] = { .desc = "Booking Delete", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_HP_INFO_1] = { .desc = "Party Hp Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_ADD_OTHER_1] = { .desc = "Deal Add Other", .size = 20, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::OPEN_BUYING_STORE] = { .desc = "Open Buying Store", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::OPEN_BUYING_STORE_FAIL] = { .desc = "Open Buying Store Fail", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::OPEN_BUYING_STORE_ITEM_LIST] = { .desc = "Open Buying Store Item List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::BUYING_STORE_FOUND] = { .desc = "Buying Store Found", .size = 86, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BUYING_STORE_LOST] = { .desc = "Buying Store Lost", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BUYING_STORE_ITEMS_LIST_0] = { .desc = "Buying Store Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::BUYING_BUY_FAIL] = { .desc = "Buying Buy Fail", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BUYING_STORE_UPDATE] = { .desc = "Buying Store Update", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::BUYING_STORE_ITEM_DELETE] = { .desc = "Buying Store Item Delete", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ELEMENTAL_INFO] = { .desc = "Elemental Info", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO_6] = { .desc = "Stat Info", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BUYING_STORE_FAIL] = { .desc = "Buying Store Fail", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CHAR_DELETE2_RESULT] = { .desc = "Char Delete2 Result", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAR_DELETE2_ACCEPT_RESULT] = { .desc = "Char Delete2 Accept Result", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAR_DELETE2_CANCEL_RESULT] = { .desc = "Char Delete2 Cancel Result", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RECEIVED_CHARACTERS_INFO_1] = { .desc = "Received Characters Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SEARCH_STORE_RESULT] = { .desc = "Search Store Result", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SEARCH_STORE_FAIL] = { .desc = "Search Store Fail", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_EXPULSION_1] = { .desc = "Guild Expulsion", .size = 66, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SEARCH_STORE_OPEN] = { .desc = "Search Store Open", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SEARCH_STORE_POS] = { .desc = "Search Store Pos", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_ERROR_1] = { .desc = "Login Error", .size = 26, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CASH_SHOP_OPEN_RESULT] = { .desc = "Cash Shop Open Result", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CASH_SHOP_BUY_RESULT] = { .desc = "Cash Shop Buy Result", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ITEM_APPEARED_1] = { .desc = "Item Appeared", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_MOVED_5] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_5] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_CONNECTED_5] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SHOW_EQ_1] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::UNKNOWN_0] = { .desc = "Unknown", .size = 2, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SHOW_SCRIPT] = { .desc = "Show Script", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PET_CAPTURE_PROCESS_1] = { .desc = "Pet Capture Process", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::PET_CAPTURE_RESULT_1] = { .desc = "Pet Capture Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_PIN_CODE_REQUEST_1] = { .desc = "Login Pin Code Request", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_PIN_NEW_CODE_RESULT] = { .desc = "Login Pin New Code Result", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::AREA_SPELL_2] = { .desc = "Area Spell", .size = 19, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_ACTION_2] = { .desc = "Actor Action", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CASH_SHOP_LIST] = { .desc = "Cash Shop List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RATES_INFO] = { .desc = "Rates Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_MOVEMENT_INTERRUPTED_1] = { .desc = "Actor Movement Interrupted", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REVOLVING_ENTITY_2] = { .desc = "Revolving Entity", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HIGH_JUMP_1] = { .desc = "High Jump", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NAVIGATE_TO] = { .desc = "Navigate To", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::QUEST_UPDATE_MISSION_HUNT_1] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_STATUS_ACTIVE_2] = { .desc = "Actor Status Active", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_STACKABLE_3] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_NONSTACKABLE_3] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_STACKABLE_3] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_NONSTACKABLE_3] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SHOW_EQ_2] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEM_FAVORITE] = { .desc = "Inventory Item Favorite", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_CONNECTED_6] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_MOVED_6] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_6] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MERGE_ITEM_OPEN] = { .desc = "Merge Item Open", .size = 4, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MERGE_ITEM_RESULT] = { .desc = "Merge Item Result", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_STACKABLE_3] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_NONSTACKABLE_4] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MONSTER_HP_INFO] = { .desc = "Monster Hp Info", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ALL_LIST_1] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RATES_INFO2] = { .desc = "Rates Info2", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::TOP10] = { .desc = "Top10", .size = 4, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::RANK_POINTS] = { .desc = "Rank Points", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_STATUS_ACTIVE_3] = { .desc = "Actor Status Active", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_STATUS_ACTIVE_4] = { .desc = "Actor Status Active", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_POST_DELAYLIST_1] = { .desc = "Skill Post Delaylist", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CLAN_USER] = { .desc = "Clan User", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CLAN_INFO] = { .desc = "Clan Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CLAN_LEAVE] = { .desc = "Clan Leave", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::CLAN_CHAT] = { .desc = "Clan Chat", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEM_ADDED_3] = { .desc = "Inventory Item Added", .size = 31, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::INVENTORY_ITEMS_STACKABLE_4] = { .desc = "Inventory Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEMS_NONSTACKABLE_4] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_STACKABLE_4] = { .desc = "Cart Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_NONSTACKABLE_4] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_STACKABLE_4] = { .desc = "Storage Items Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_NONSTACKABLE_5] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SHOW_EQ_3] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::EQUIP_ITEM_1] = { .desc = "Equip Item", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::UNEQUIP_ITEM_1] = { .desc = "Unequip Item", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_PROPERTY_3] = { .desc = "Map Property3", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RECEIVED_CHARACTERS_1] = { .desc = "Received Characters", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::AREA_SPELL_MULTIPLE2] = { .desc = "Area Spell Multiple2", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SYNC_RECEIVED_CHARACTERS] = { .desc = "Sync Received Characters", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BANKING_CHECK] = { .desc = "Banking Check", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BANKING_DEPOSIT] = { .desc = "Banking Deposit", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::BANKING_WITHDRAW] = { .desc = "Banking Withdraw", .size = 16, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_OPENED_1] = { .desc = "Storage Opened", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_CLOSED_1] = { .desc = "Storage Closed", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::AREA_SPELL_MULTIPLE3] = { .desc = "Area Spell Multiple3", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SKILL_USED_NO_DAMAGE_1] = { .desc = "Skill Used No Damage", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MESSAGE_STRING_2] = { .desc = "Message String", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GAMEGUARD_REQUEST_2] = { .desc = "Gameguard Request", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PROGRESS_BAR_UNIT] = { .desc = "Progress Bar Unit", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_MARKET_INFO] = { .desc = "Npc Market Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::NPC_MARKET_PURCHASE_RESULT] = { .desc = "Npc Market Purchase Result", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_STORAGE_LOG] = { .desc = "Guild Storage Log", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_MOVED_7] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_CONNECTED_7] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_7] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PRIVATE_MESSAGE_1] = { .desc = "Private Message", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PRIVATE_MESSAGE_SENT_1] = { .desc = "Private Message Sent", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SHOP_SOLD_LONG] = { .desc = "Shop Sold Long", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::UNREAD_RODEX] = { .desc = "Unread Rodex", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RODEX_READ_MAIL] = { .desc = "Rodex Read Mail", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RODEX_WRITE_RESULT] = { .desc = "Rodex Write Result", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RODEX_MAIL_LIST_0] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RODEX_GET_ZENY] = { .desc = "Rodex Get Zeny", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RODEX_GET_ITEM] = { .desc = "Rodex Get Item", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RODEX_DELETE] = { .desc = "Rodex Delete", .size = 11, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HOMUNCULUS_PROPERTY_1] = { .desc = "Homunculus Property", .size = 77, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ALL_LIST_2] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ADD_1] = { .desc = "Quest Add", .size = 17, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::QUEST_UPDATE_MISSION_HUNT_2] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PET_EVOLUTION_RESULT] = { .desc = "Pet Evolution Result", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACTOR_MOVED_8] = { .desc = "Actor Moved", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_CONNECTED_8] = { .desc = "Actor Connected", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_EXISTS_8] = { .desc = "Actor Exists", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::HOTKEYS_2] = { .desc = "Hotkeys", .size = 3, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::RODEX_ADD_ITEM] = { .desc = "Rodex Add Item", .size = 53, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::RODEX_REMOVE_ITEM] = { .desc = "Rodex Remove Item", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_ADD_OTHER_2] = { .desc = "Deal Add Other", .size = 45, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::STORAGE_ITEM_ADDED_2] = { .desc = "Storage Item Added", .size = 47, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CART_ITEM_ADDED_2] = { .desc = "Cart Item Added", .size = 47, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::INVENTORY_ITEM_ADDED_4] = { .desc = "Inventory Item Added", .size = 56, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::INVENTORY_ITEMS_NONSTACKABLE_5] = { .desc = "Inventory Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEMS_NONSTACKABLE_5] = { .desc = "Cart Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEMS_NONSTACKABLE_6] = { .desc = "Storage Items Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RODEX_OPEN_WRITE] = { .desc = "Rodex Open Write", .size = 27, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RODEX_CHECK_PLAYER_0] = { .desc = "Rodex Check Player", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GOLD_PC_CAFE_POINT] = { .desc = "Gold Pc Cafe Point", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DYNAMICNPC_CREATE_RESULT] = { .desc = "Dynamicnpc Create Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_LOADED_2] = { .desc = "Map Loaded", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ROULETTE_WINDOW] = { .desc = "Roulette Window", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ROULETTE_INFO] = { .desc = "Roulette Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ROULETTE_WINDOW_UPDATE] = { .desc = "Roulette Window Update", .size = 21, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ROULETTE_RECV_ITEM] = { .desc = "Roulette Recv Item", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ACHIEVEMENT_LIST] = { .desc = "Achievement List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACHIEVEMENT_UPDATE] = { .desc = "Achievement Update", .size = 66, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACHIEVEMENT_REWARD_ACK] = { .desc = "Achievement Reward Ack", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HP_SP_CHANGED_1] = { .desc = "Hp Sp Changed", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::OPEN_STORE_STATUS] = { .desc = "Open Store Status", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SHOW_EQ_4] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CHANGE_TITLE] = { .desc = "Change Title", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_INFO_2] = { .desc = "Actor Info", .size = 106, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SENBEI_AMOUNT] = { .desc = "Senbei Amount", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MONSTER_HP_INFO_TINY] = { .desc = "Monster Hp Info Tiny", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEM_ADDED_5] = { .desc = "Inventory Item Added", .size = 69, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::OPEN_UI_0] = { .desc = "Open Ui", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HAT_EFFECT] = { .desc = "Hat Effect", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PARTY_JOIN_2] = { .desc = "Party Join", .size = 85, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_USERS_INFO_1] = { .desc = "Party Users Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::STYLIST_RES] = { .desc = "Stylist Res", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PRIVATE_AIRSHIP_TYPE] = { .desc = "Private Airship Type", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_CHANGE_1] = { .desc = "Map Change", .size = 22, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_CHANGED_1] = { .desc = "Map Changed", .size = 28, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RODEX_CHECK_PLAYER_1] = { .desc = "Rodex Check Player", .size = 34, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CAPTCHA_UPLOAD_REQUEST] = { .desc = "Captcha Upload Request", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CAPTCHA_UPLOAD_REQUEST_STATUS] = { .desc = "Captcha Upload Request Status", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::MACRO_REPORTER_STATUS] = { .desc = "Macro Reporter Status", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MACRO_DETECTOR] = { .desc = "Macro Detector", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MACRO_DETECTOR_IMAGE] = { .desc = "Macro Detector Image", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MACRO_DETECTOR_SHOW] = { .desc = "Macro Detector Show", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MACRO_DETECTOR_STATUS] = { .desc = "Macro Detector Status", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CAPTCHA_PREVIEW] = { .desc = "Captcha Preview", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CAPTCHA_PREVIEW_IMAGE] = { .desc = "Captcha Preview Image", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MACRO_REPORTER_SELECT] = { .desc = "Macro Reporter Select", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MESSAGE_STRING_3] = { .desc = "Message String", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::EAC_KEY] = { .desc = "Eac Key", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr };
    packet_map[PacketInfo::RODEX_MAIL_LIST_1] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_EXPULSION_2] = { .desc = "Guild Expulsion", .size = 46, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_LEAVE_1] = { .desc = "Guild Leave", .size = 46, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_INFO_2] = { .desc = "Guild Info", .size = 94, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::OFFLINE_CLONE_FOUND_0] = { .desc = "Offline Clone Found", .size = 57, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::OFFLINE_CLONE_LOST] = { .desc = "Offline Clone Lost", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::VENDER_ITEMS_LIST_2] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::BUYING_STORE_ITEMS_LIST_1] = { .desc = "Buying Store Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MISC_CONFIG_0] = { .desc = "Misc Config", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::DEAL_ADD_OTHER_3] = { .desc = "Deal Add Other", .size = 61, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::EQUIP_ITEM_SWITCH] = { .desc = "Equip Item Switch", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::UNEQUIP_ITEM_SWITCH] = { .desc = "Unequip Item Switch", .size = 9, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::EQUIP_SWITCH_LOG] = { .desc = "Equip Switch Log", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::EQUIP_SWITCH_RUN_RES] = { .desc = "Equip Switch Run Res", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REFINEUI_OPENE] = { .desc = "Refineui Opene", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::REFINEUI_INFO] = { .desc = "Refineui Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBERS_LIST_1] = { .desc = "Guild Members List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::MISC_CONFIG_1] = { .desc = "Misc Config", .size = 5, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_DEAD] = { .desc = "Party Dead", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MOVE_INTERRUPT] = { .desc = "Move Interrupt", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::ITEM_PREVIEW_0] = { .desc = "Item Preview", .size = 39, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::PARTYLV_INFO] = { .desc = "Partylv Info", .size = 10, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::WARP_PORTAL_LIST_1] = { .desc = "Warp Portal List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RODEX_MAIL_LIST_2] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACCOUNT_SERVER_INFO_2] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RECEIVED_CHARACTER_ID_AND_MAP_1] = { .desc = "Received Character Id And Map", .size = 156, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MAP_CHANGED_2] = { .desc = "Map Changed", .size = 156, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACCOUNT_SERVER_INFO_3] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ERRORS_1] = { .desc = "Errors", .size = 3, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STAT_INFO_7] = { .desc = "Stat Info", .size = 12, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::EXP_1] = { .desc = "Exp", .size = 18, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_ERROR_2] = { .desc = "Login Error", .size = 23, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REFINE_STATUS] = { .desc = "Refine Status", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::MISC_CONFIG_2] = { .desc = "Misc Config", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_APPEARED_2] = { .desc = "Item Appeared", .size = 24, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::OVERWEIGHT_PERCENT] = { .desc = "Overweight Percent", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ACTOR_INFO_3] = { .desc = "Actor Info", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOGIN_ERROR_3] = { .desc = "Login Error", .size = 30, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::OPEN_UI_1] = { .desc = "Open Ui", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::RECEIVED_LOGIN_TOKEN] = { .desc = "Received Login Token", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::PARTY_JOIN_3] = { .desc = "Party Join", .size = 89, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PARTY_USERS_INFO_2] = { .desc = "Party Users Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACTION_UI] = { .desc = "Action Ui", .size = 7, .type = PacketSizeType::FIXED, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::CHARACTER_NAME_1] = { .desc = "Character Name", .size = 32, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SAGE_AUTOSPELL_2] = { .desc = "Sage Autospell", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_POSITION] = { .desc = "Guild Position", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::QUEST_UPDATE_MISSION_HUNT_3] = { .desc = "Quest Update Mission Hunt", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ALL_LIST_3] = { .desc = "Quest All List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SHOW_EQ_5] = { .desc = "Show Eq", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::OFFLINE_CLONE_FOUND_1] = { .desc = "Offline Clone Found", .size = 63, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_LIST_START] = { .desc = "Item List Start", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ITEM_LIST_STACKABLE] = { .desc = "Item List Stackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ITEM_LIST_NONSTACKABLE_0] = { .desc = "Item List Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ITEM_LIST_END] = { .desc = "Item List End", .size = 4, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::QUEST_ADD_2] = { .desc = "Quest Add", .size = 155, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_PREVIEW_1] = { .desc = "Item Preview", .size = 48, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_EXPANSION_RESULT] = { .desc = "Inventory Expansion Result", .size = 6, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_CAST_2] = { .desc = "Skill Cast", .size = 29, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::LOAD_CONFIRM] = { .desc = "Load Confirm", .size = 2, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::PING] = { .desc = "Ping", .size = -1, .type = PacketSizeType::UNKNOWN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::HOTKEYS_3] = { .desc = "Hotkeys", .size = 271, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HOMUNCULUS_PROPERTY_2] = { .desc = "Homunculus Property", .size = 73, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILL_ADD_1] = { .desc = "Skill Add", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::SKILLS_LIST_3] = { .desc = "Skills List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::SKILL_UPDATE_3] = { .desc = "Skill Update", .size = 17, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::ITEM_LIST_NONSTACKABLE_1] = { .desc = "Item List Nonstackable", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::VENDER_ITEMS_LIST_3] = { .desc = "Vender Items List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::INVENTORY_ITEM_ADDED_6] = { .desc = "Inventory Item Added", .size = 70, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::STORAGE_ITEM_ADDED_3] = { .desc = "Storage Item Added", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CART_ITEM_ADDED_3] = { .desc = "Cart Item Added", .size = 58, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::CHAR_EMBLEM_UPDATE] = { .desc = "Char Emblem Update", .size = 14, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::UNKNOWN_1] = { .desc = "Unknown", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::RODEX_MAIL_LIST_3] = { .desc = "Rodex Mail List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::ACCOUNT_SERVER_INFO_4] = { .desc = "Account Server Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::CHARACTER_CREATION_SUCCESSFUL_1] = { .desc = "Character Creation Successful", .size = 2, .type = PacketSizeType::FIXED_MIN, .handler = nullptr, .alert = true };
    packet_map[PacketInfo::RECEIVED_CHARACTERS_2] = { .desc = "Received Characters", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::REVOLVING_ENTITY_3] = { .desc = "Revolving Entity", .size = 8, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::HOMUNCULUS_PROPERTY_3] = { .desc = "Homunculus Property", .size = 77, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::NPC_STORE_INFO_1] = { .desc = "Npc Store Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_INFO_3] = { .desc = "Guild Info", .size = 118, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::GUILD_EXPULSION_LIST_1] = { .desc = "Guild Expulsion List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBERS_LIST_2] = { .desc = "Guild Members List", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::GUILD_MEMBER_ADD_1] = { .desc = "Guild Member Add", .size = 60, .type = PacketSizeType::FIXED, .handler = nullptr };
    packet_map[PacketInfo::REPUTE_INFO] = { .desc = "Repute Info", .size = -1, .type = PacketSizeType::INDICATED_IN_PACKET, .handler = nullptr };
    packet_map[PacketInfo::HOMUNCULUS_PROPERTY_4] = { .desc = "Homunculus Property", .size = 85, .type = PacketSizeType::FIXED, .handler = nullptr };
    
}
